namespace BudganInfra.Repositories.AccountTransaction.GetListByAccount;

public interface IListAccountTransactionByAccountRepoOp : IRepositoryOperationWithResultValue<List<DaoListByAccountAccountTransaction>>
{
}
