# This is a generated file. Not intended for manual editing.
services:
  budgansvr-release:
    build:
      context: "/Users/dannyt/dev/BudganSvr/BudganSvr"
      dockerfile: "BudganSvr/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/BudganSvr.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net10.0/BudganSvr.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "budgansvr:dev"
    ports: []
    volumes:
    - "/Users/dannyt/dev/BudganSvr/BudganSvr/BudganSvr:/app:rw"
    - "/Users/dannyt/dev/BudganSvr/BudganSvr:/src:rw"
    - "/Users/dannyt/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
